version: '3.4'

services:
  poc-nosql:
    image: ${DOCKER_REGISTRY-}pocnosql
    build:
      context: .
      dockerfile: src/Poc-NoSql/Dockerfile
    depends_on:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: secret

